apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  namespace: ai-defense-trainer
  labels:
    app: workers
    component: processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
        component: processing
    spec:
      containers:
      - name: workers
        image: ai-defense-trainer/workers:latest
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: nats-url
        - name: CLICKHOUSE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: clickhouse-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: openai-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: anthropic-key
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: email-secrets
              key: sendgrid-key
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: sms-secrets
              key: twilio-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: sms-secrets
              key: twilio-token
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: workers-service
  namespace: ai-defense-trainer
  labels:
    app: workers
spec:
  selector:
    app: workers
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
